theme: jekyll-theme-architect
title: Pymanujan
description: Check out the Github repository too. Good stuff over there too!
show_downloads: true
zip_url: https://github.com/tsadarsh/Pymanujan/releases/download/v2.0/Pymanujan.zip
